#!/usr/bin/ruby

# if ENV["XDG_CONFIG_HOME"] != ""
#     if File.directory? "#{ENV['XDG_CONFIG_HOME']}/vim"
#         vim_dir = "#{ENV['XDG_CONFIG_HOME']}/vim"
#     else
#         if File.directory? "#{ENV['HOME']}/.vim"
#             vim_dir = "#{ENV['HOME']}/.vim"
#         end
#     end
# else
#     if File.directory? "#{ENV['HOME']}/.config/vim"
#         vim_dir = "#{ENV['HOME']}/.config/vim"
#     end
#     if File.directory? "#{ENV['HOME']}/.vim"
#         vim_dir = "#{ENV['HOME']}/.vim"
#     end
# end
# 
# if File.directory? 
# end

plugins = [
    "https://github.com/bling/vim-airline",
    "https://github.com/paranoida/vim-airlineish",
    "https://github.com/Shougo/neocomplete",
    "https://github.com/kana/vim-textobj-user",
    "https://github.com/ntpeters/vim-better-whitespace",
    "https://github.com/kana/vim-smartinput",
    "https://github.com/kien/ctrlp.vim",
    "https://github.com/scrooloose/syntastic",
    "https://github.com/godlygeek/tabular",
    "https://github.com/suxpert/vimcaps",
    "https://github.com/matchit.zip",
    "https://github.com/justinmk/vim-sneak",
    "https://github.com/tommcdo/vim-exchange",
    "https://github.com/nelstrom/vim-markdown-folding",
    "https://github.com/lilydjwg/colorizer",
    "https://github.com/tpope/vim-abolish",
    "https://github.com/tpope/vim-commentary",
    "https://github.com/tpope/vim-eunuch",
    "https://github.com/tpope/vim-fugitive",
    "https://github.com/tpope/vim-obsession",
    "https://github.com/tpope/vim-repeat",
    "https://github.com/tpope/vim-surround",
    "https://github.com/tpope/vim-vinegar",
    "https://github.com/tpope/vim-markdown",
    "https://github.com/Matt-Stevens/vim-systemd-syntax",
    "https://github.com/Shougo/neosnippet",
    "https://github.com/Shougo/neosnippet-snippets",
    "https://github.com/airblade/vim-gitgutter",
    "https://github.com/gcmt/wildfire.vim",
    "https://github.com/tpope/vim-pathogen",
    "https://github.com/kana/vim-textobj-entire"
]


case ARGV[0]
when "init"
    plugins.each { | i |
        `git submodule add '#{i}' > /dev/null`
    }
when "update"
    `git submodule foreach git pull origin master`
when "add"
    plugins.push( ARGV[1] )
    `git submodule add #{ARGV[1]}`
end
